### ISSUE TITLE
Hover editor does not triggered upon embeds in Obsidian v1.0.0 (reading view)

### ISSUE THREAD

**Issue by mmdzt** [nothingislost/obsidian-hover-editor#183]
After I update the obsidian, the hover editor does not triggered upon embeds in Obsidian v1.0.0 (reading view)

**Comment by mmdzt** [comment]
Thanks for reading

**Comment by pjeby** [comment]
What version of Hover Editor are you using?

**Comment by mmdzt** [comment]
> What version of Hover Editor are you using?

version  0.11.4

**Comment by pjeby** [comment]
Are you using the Ctrl/Cmd key when hovering?  What are your Page Preview settings configured to use?

(Also, I assume you are referring to hovering over *links* contained in embeds, since as far as I know hovering embeds *themselves* doesn't do anything in reading mode, even in Obsidian 0.15.)

**Comment by mmdzt** [comment]
I use the Ctrl/Cmd key when hovering, and the buttons Page Preview settings are all on. But I may misunderstand the meaning of "Trigger hover preview on embeds". Sorry to bother you, and thanks for your patience. Here is what I want.

![image](https://user-images.githubusercontent.com/90957271/196710772-1ff6ce38-b85e-4339-92b1-823aca2189c1.png)

Actually, I'm hoping to use the hover function when I was reading the lists collected by 'dataview', since there may be some context I may need to read near the list. So I open the setting of the hover editor to see if there are any options that can implement this function. That's when I found the "Trigger hover preview on embeds" which I thought may trigger the hover preview over the content that was embedded (not over the link) in reading mode. However, I may misunderstand the meaning as you say "hovering embeds themselves don't do anything in reading mode". But thanks again! I love hover editor and thank you for creating it!

**Comment by pjeby** [comment]
Ah, didn't realize you were using the embeds option - I actually forgot that option existed.  And I can now reproduce the problem.  It looks like there was an internal API change in Obsidian that broke this; some additional work will be needed to find out what and how to work around it.

**Comment by pjeby** [comment]
This should now be fixed in the 0.11.6 release.

**Comment by mmdzt** [comment]
> This should now be fixed in the 0.11.6 release.

Fantastic! Thank you very much!!! And wish you a wonderful day!!!!!

**Comment by mmdzt** [comment]
I'm sorry, but I still have a question: Is it possible to trigger hover preview on the lists collected by dataview? Cause I tested the embeds option, it works on embedded information using code like `![]`, but it didn't work on the lists collected by dataview.

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/90957271/196860574-81285ce9-1533-4637-9da2-36025c99c1fa.png">
 
♥️♥️♥️ Thanks for your patience!

**Comment by mmdzt** [comment]
Here is the code I used in the picture up there

```dataview
task
from "+ Encounters"
```

**Comment by pjeby** [comment]
That would be something that would need to be added in Dataview, to generate the `hover-link` events Obsidian uses to trigger page previews.  (That is, if Dataview adds support for the built-in page preview, then it should work with Hover Editor as well.)

**Comment by mmdzt** [comment]
Okay, got it. Thanks a bunch! 😃
